Work branch
Josphat205/hello-rails-backend pull request #1
Opened 2023-05-05 06:35 UTC by Josphat205

- Created a new Rails API app called 'hello-rails-back-end'.
- Initialized your project with Git.
- make sure that your project has a Postgres database set up.
- Created a table for storing your messages and create 5 different greetings.
- Created an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

2023-05-05 08:19 UTC, Ismailco requested changes
### Hi @Josphat205, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
- [x] Kindly make sure all the links in your README file are working properly, the LICENSE does not exist in the repo, kindly consider adding a LICENSE and edit the name from `LICENSE.txt` to `LICENSE` so GitHub can automatically detect it and associate it with this repo
- [x] The Front end produces an error because you're trying to render the greeting message before it's fetched from the API, which produces an error of `message` undefined. I highly suggest moving the logic (fetch message) from the `Home` component into the Reducer (redux) or adding a condition before rendering the message like so: 

```javascript
 {greeting.message && (
        <p>
          {greeting.message.message} posted on {greeting.message.created_at}
        </p>
      )}
```  
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 08:19 UTC, Ismailco commented on README.md
> +This project is [MIT](LICENSE.txt) licensed.
- [ ] Kindly make sure all the links in your README file are working properly, the LICENSE does not exist in the repo, kindly consider adding a LICENSE and edit the name from `LICENSE.txt` to `LICENSE` so GitHub can automatically detect it and associate it with this repo

2023-05-05 08:19 UTC, Ismailco commented on app/models/greeting.rb
> +  # frozen_string_literal: true
- [ ] Kindly make sure to remove old commented code from your repo so it appear clean and easy to navigate

2023-05-06 06:39 UTC, Kamba56 requested changes
Hi @Josphat205, 

Great work on making the changes requested by a previous reviewer 👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Great job consuming the greetings API!👏👏👏
- [x] !👏👏👏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 06:39 UTC, Kamba56 commented on app/models/greeting.rb
> +  validates :name, presence: true
- [ ] There is no name field in the greetings table. I notice you are validating for the presence of a name while there is no name in the greetings table. Kindly remove this please as it is returning an error.

2023-05-06 07:29 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Josphat205 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="275px" />

## Highlights :heavy_check_mark: 
- [x] Implemented all the changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 08:01 UTC, merged